### ISSUE TITLE
add support for args/kwargs magic params

### ISSUE THREAD

**Issue by bbinet** [saltstack/halite#119]
Recently, I have developped a custom module that makes use of python args/kwargs magic params. The problem is that when I want to use this module through Halite, there is no way to pass custom args/kwargs params in the web interface.
For example, you can try with the "test.arg" module (which simply return the args/kwargs params) in Halite: there is no way to specify values for args/kwargs.

See: https://groups.google.com/d/topic/salt-users/FLhe82b5sEY/discussion

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
