### ISSUE TITLE
preserve output format

### ISSUE THREAD

**Issue by volos** [saltstack/halite#123]
I tried to push the change to the git repository but access is denied so here is the suggestion:

preserve the output format of the job 
by changing console.html  

line 605  &lt;n>{{value}}{{!$last ? " ," : ""}}&lt;/n>
 to use tag &lt;pre&gt; instead

![image](https://f.cloud.github.com/assets/499258/2133081/1c5077a6-92bc-11e3-9eda-d9ed27a27b8c.png)

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
