### ISSUE TITLE
Show pretty requirements via d3

### ISSUE THREAD

**Issue by SEJeff** [saltstack/halite#15]
The [d3 layout tree](http://mbostock.github.io/d3/talk/20111018/tree.html) is a fantastic javascript widget for showing dependencies. Click the various nodes and watch them expand.

It would be awesome to do this for overstate (on a group of minions) and highstate for a single one.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
