### ISSUE TITLE
All webpages when using halite sometimes randomly shows a lot of junk

### ISSUE THREAD

**Issue by nmadhok** [saltstack/halite#177]
All Webpage when using halite randomly shows a lot of junk. Tested on Safari and Google Chrome. Restarted the browsers but the problem occasionally occurs. Please see some of the attached screenshots below:

![screen shot 2014-06-02 at 10 35 15 am](https://cloud.githubusercontent.com/assets/3374962/3148676/2bf2339e-ea63-11e3-8961-0ffd85ee7d32.png)

![screen shot 2014-06-02 at 10 38 17 am](https://cloud.githubusercontent.com/assets/3374962/3148709/904fe7a0-ea63-11e3-9bed-b2c36f9c4917.png)

![screen shot 2014-06-02 at 10 39 19 am](https://cloud.githubusercontent.com/assets/3374962/3148731/b8f27006-ea63-11e3-85bc-db1ca802a6ba.png)

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
