### ISSUE TITLE
Failed to authenticate, is this user permitted to execute commands?

### ISSUE THREAD

**Issue by Aaron1989** [saltstack/halite#180]
[root@ config]# salt-key -L
Accepted Keys:
salt.minion1.org
Unaccepted Keys:
Rejected Keys:
[root@ config]# vi /etc/salt/master.d 

rest_cherrypy:
 host: 0.0.0.0
 port: 8080
 debug: true
 disable_ssl: True
 static: /var/www/halite/halite
 app: /var/www/halite/halite/index.html

external_auth:
   pam:
     aaron:
     - .*
     - '@runner'
     - '@wheel'

这是我配置文件信息，不过用aaron账号向minion发送test.ping报错，不知道哪里照收debug。。。
[root@ config]# salt -a pam *  test.ping
username: aaron
password: 
Failed to authenticate, is this user permitted to execute commands?

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
