### ISSUE TITLE
Halite does not respect base prefix

### ISSUE THREAD

**Issue by Imtnt** [saltstack/halite#183]
Halite seems to absolutely refuses to respect any base path such as '/halite/' specified either in the salt master config or in arguments specified in explicitly when running it directly.  It at least claims to rebase them when I specify to do so while running it directly, but it's actions say otherwise.  For example, when I give it the url /halite/app/console and set the base to /halite/ it resolves and loads the page, but then immediately changes the url to /app/console which of course doesn't exist.  Just to clarify it doesn't even get that far when I try to specify base in the config as it won't so much as resolve the url and instead gives me a delightful 404.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
