### ISSUE TITLE
Halite Debian Install Notes

### ISSUE THREAD

**Issue by gargolito** [saltstack/halite#188]
Not a problem but I had some issues installing Halite on debian 7.7 and this is how I troubleshoot and resolved.

The installation info from docs.saltstack.com fail at some points due to undocumented missing libraries, the steps below should succesfully complete the installation.
1. apt-get install libffi-dev gcc python-dev libevent-dev python-pip
2. curl https://bootstrap.pypa.io/ez_setup.py | python
3. pip install -U halite pyopenssl gevent CherryPy paste

Do _only_ steps 3.6.1.3 and 3.6.1.4 from http://docs.saltstack.com/en/latest/topics/tutorials/halite.html
_make sure you do: salt-call tls.create_self_signed_cert tls_

At this point you have everything you need, but Halite will not start. After following the troubleshooting steps from _https://github.com/saltstack/halite/issues/166_ I discovered that on starting salt-master, the webserver was asking for the PEM password. To resolve this just strip the PEM password from the key file:
1. cd /etc/pki/tls/certs/
2. mv localhost.key localhost.key.pw
3. openssl rsa -in localhost.key.pw -out localhost.key
4. /etc/init.d/salt-master restart

**Comment by tbaschak** [comment]
Thanks for the tip about removing the password from the key.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
