### ISSUE TITLE
Project being dead is unclear from repo info

### ISSUE THREAD

**Issue by froztbyte** [saltstack/halite#194]
The repo description, as well as the readme, should probably (high on the list) contain some info showing that Halite is no longer supported/developed.

**Comment by iggy** [comment]
The second sentence in the tame says it's retired. If you want to submit a PR to make it a big bold highlighted color warning, it would probably get merged.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
