### ISSUE TITLE
halite cmd.run error  cmd.run: unsupported operand type(s) for +: 'float' and 'str'. 

### ISSUE THREAD

**Issue by minminmsn** [saltstack/halite#196]
cmd.rum
error:
TypeError encountered executing cmd.run: unsupported operand type(s) for +: 'float' and 'str'. See debug log for more info.

**Comment by UtahDave** [comment]
I'm so sorry. This halite project has been retired and is no longer under active development.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
