### ISSUE TITLE
Fetch grains from all minions button: some KOs

### ISSUE THREAD

**Issue by PierreR** [saltstack/halite#42]
settings : local with 2 minions
halite version: 2ee247b

The main issue here is the button that keeps spinning when a minion is down. Do we really want that ?
## Detailed behavior :
- starting Halite with one minion up, one minion down
  - KO: the button keeps spinning forever
  - KO: grain labels of the "up" minion" (green) are there but no data
- restart the `down` minion:
  - OK: the button stops spining
  - OK: minion previously down is marked as up and all grains info are received
  - KO: the second minion (that has been up all the time) still doesn't have the grain values.
- push the fetch grains button -> OK: expected behavior, all grains info are displayed.
- stop one of them again and press the refresh button
  - OK: status is red, all grain info are still displayed
  - KO: the "fetch grains button" next to the "refresh" button keeps spinning again

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
