### ISSUE TITLE
When starting halite as part of the salt-master service, logs are continually pushed to existing shell session.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/halite#50]
When halite is configured via the /etc/salt/master file, and then started automatically when you start/restart the salt-master service (running as root in this instance), the log data from the web server logs directly to the shell session. This occurs regardless of log level, and requires that the user close the existing session and reconnect.

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
