### ISSUE TITLE
Halite only starts with salt-master running in the foreground

### ISSUE THREAD

**Issue by techhat** [saltstack/halite#52]
Halite starts when starting the salt-master in the foreground, but when running in the background it never starts up.
'''
[root@dufresne network.d]# salt-master --versions-report
           Salt: 0.17.0-1446-g521ccda
         Python: 2.7.5 (default, Sep  6 2013, 09:55:21)
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.3.0
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.1.0
            ZMQ: 4.0.1
[root@dufresne network.d]# pacman -Q | grep halite
halite 0.1.02-2
'''

**Comment by rallytime** [comment]
This repo is deprecated and archived. Therefore, this issue is now closed. Thank you.
