### ISSUE TITLE
Halite documentation

### ISSUE THREAD

**Issue by pguay** [saltstack/halite#78]
When you have to generate the certificate for Halite (in the docs https://salt.readthedocs.org/en/latest/topics/tutorials/halite.html), the command doesn't work :
salt '*' tls.create_self_signed_cert test

It is supposed to be :
salt-call tls.create_self_signed_cert tls

**Comment by jasonmcintosh** [comment]
Note, that on systems installed with the EPEL, you need to make sure pyOpenSSL is installed as that does NOT come in by default.  salt-call fails until you do.  Might be good to update the docs to include that as well.

**Comment by orangebjung** [comment]
@jasonmcintosh true. the documentation doesn't tell about it.
plus, my question is... so to run halite, is it mandatory for the master to have itself as accepted minion?
